- hosts: serveur01
  tasks:
  - name: Ensure epel repository is set
    yum:
      name: epel-release
      state: latest
    become: true
    
  - name: auto
    package_facts:
    manager: auto

  # System update
  - name: Ensure all pkgs are up-to-date
    yum:
      name: '*'
      state: latest
    become: true
    tags: update

  # Install packages
  - name: Installation test
    debug:
      yum:
        pkg: "{{ item }}"
        state: latest
        become: true
      when: "{{ item }} not in ansible_facts.packages"
      with_items:
        - telnet
        - mailx
        - postfixadmin
