---
- hosts: serveur01
    # Install packages
- package_facts:
    manager: yum
- name: installation des pachkage
  tasks:
    debug:
      yum:
        pkg: "{{ item }}"
        state: latest
      become: true
    when: "{{ item }} not in ansible_facts.packages"
    with_items:
        - telnet
        - mailx
        - postfixadmin
...
