- hosts: serveur01
  tasks:
    # Install packages
    - name: test installation validation
      package_facts:
          manager: yum
          debug:
            yum:
              pkg: "{{ item }}"
              state: latest
          when: "{{ item }} not in ansible_facts.packages"
          become: true
          with_items:
              - telnet
              - mailx
              - postfixadmin
